### PR TITLE
New slider component

### PR DESCRIPTION
**Pull request by duduBTW**
- Add new slider component
- Fix duration issue by using the state on the seek function.
- Fix issue were the songs would skip infinitely if you hold seeked to the end of the song progress.
- Add support for scroll slide.

https://github.com/user-attachments/assets/839f64af-b229-4e7f-b66e-fdacc4101229

### CODE REVIEW

**Comment by Tnixc** [comment]
Maybe disable the animation if triggered by keypress(holding down the key in the vide)

Also the left and right arrow keypresses doesn't seem to work unless the slider head is focused

https://github.com/user-attachments/assets/9fc4beaa-118f-4142-ae38-8d0b8ae14c7a

**Comment by duduBTW** [comment]
> Maybe disable the animation if triggered by keypress(holding down the key in the video)

This is what happens when I hold the arrow keys, works normally.

https://github.com/user-attachments/assets/5514d41a-96f2-46d3-9660-451677a5526a



> Also the left and right arrow keypresses doesn't seem to work unless the slider head is focused

This is by design, the slider is only changed by arrow keys when you focus it, the focus is triggered by various things, like drag, scroll, or tabbing into it. 

To handle changing the duration globally we would need to implement it on the keyboard class.

@Tnixc

**Comment by Tnixc** [comment]
> This is what happens when I hold the arrow keys, works normally.

I think this is because the key-repeat is not as fast on your system. No comment on if you decide to change it nor not.

**Comment by duduBTW** [comment]
@Tnixc I added a `throttle` to the slider step, could you check if it is better now?

**Review by Tnixc — APPROVED** [review]
Feels good to me now.

**Pull request merged**
