### PR TITLE
Switch from npm to bun

### PR DESCRIPTION
**Pull request by brw**
Pretty self-explanatory. Any objections?

Also figured I'd update the readme too while I was at it.

### CODE REVIEW

**Review by hrfarmer — DISMISSED** [review]

**Comment by brw** [comment]
I'll wait for a few more people before putting it through image

**Review by Tnixc — APPROVED** [review]
Hell yeah

**Review by CaptSiro — CHANGES_REQUESTED** [review]
Why changing from npm to bun? What are the benefits?

**Comment by brw** [comment]
I got annoyed by how slow npm is every now and then. When I added the Solid devtools package it took two minutes to add it for some reason. Maybe a fluke as subsequent runs were faster but still nowhere near as fast as something like bun or pnpm.

I recently compared times to install the project from scratch in the sqlite PR as well (with all packages in global cache so no downloads) and npm clocked in at like 4 minutes, whereas bun was like 20 seconds and pnpm like 10 (this is with lockfile generation but still). I just prefer the UX of bun over pnpm and the binary lockfile is nice to have to avoid large diffs so I'd be fine with the slightly slower option here.

I'd say there's little reason to stick with npm other than it being the default really. Most larger scale projects use pnpm these days, or bun if they like to live a bit more on the edge (though I'd say it's plenty stable as a package manager nowadays). If having to install something is a blocker I'd be fine with using pnpm through Corepack as well which would require no installation, just a single command to enable Corepack iirc, though bun is also only a single command to install so I don't think it matters much

**Comment by CaptSiro** [comment]
I know that bun is faster than npm. Recently I have heard that bun is pretty unstable and I would trade stability over speed any time. I would like you to address the stability issue first. Is bun really as stable as npm? If not, I don't want to add it. We could opt in for pnpm if it is still faster than npm but also as stable as npm.

**Comment by brw** [comment]
I'd say Bun the package manager is plenty stable yes. I use it in all of my projects and I have yet to run into issues or major differences with npm. It's a drop-in replacement in my experience.

I imagine you've heard about Bun the runtime not being as stable which is true, but Bun the package manager is completely separated from it. You can just ignore the runtime and only use the package manager to replace npm (which is what I do in most of my projects as the runtime still generally lacks features I need).

**Review by CaptSiro — APPROVED** [review]

**Comment by CaptSiro** [comment]
Ok, using it as a package manager can be fine. Let's see how it holds up

**Comment by brw** [comment]
Sick. I'll wait to see if @duduBTW has any comments but seems good otherwise then

**Comment by brw** [comment]
das crazy

**Review by hrfarmer — APPROVED** [review]

**Comment by duduBTW** [comment]
I say go for it, we can revert back if it causes any issues.

**Comment by brw** [comment]
bet

**Pull request merged**
