### PR TITLE
Change wording so the user doesn't input their actual osu Songs folder and enters the osu! directory instead.

### PR DESCRIPTION
**Pull request by Paladynee**
The program tries to read the database file from the given folder, which is not the osu Songs folder. I tried inputting my osu Songs folder (which resides in `C:\OsuSongs\` for me) and was annoyed when it didn't work.

### CODE REVIEW

**Review by hrfarmer — APPROVED** [review]
i swear i changed this, someone else's pr mightve reverted it back to this lol

**Comment by brw** [comment]
seems like the new UI branch had the old text yea

**Comment by brw** [comment]
@Paladynee how is your osu songs folder `C:\OsuSongs\` and not located in the osu! folder? We do have support for choosing any subdirectory of the osu folder but I didn't even know you could have the songs directory stored separately lol. Is it a symlink or something?

**Comment by hrfarmer** [comment]
https://github.com/Team-BTMC/osu-radio/blob/master/src/main/main.ts#L20

we do support it, that's what i added in the db pr

**Comment by brw** [comment]
Oh it's a config option. Interesting, didn't know that existed

**Pull request merged**
