### PR TITLE
Merge feature/new-ui into master(again)

### PR DESCRIPTION
**Pull request by Tnixc**
This should work.

### CODE REVIEW

**Comment by brw** [comment]
Did you test the app as well @Tnixc? Does it work on Windows? It does not look like the app is actually starting for me on Linux using this PR, whereas both master and feature/new-ui start just fine.

**Comment by brw** [comment]
I was trying to bring this PR more in line with master by applying the Prettier changes to both branches to make the diff easier but I give up honestly. It just seems to introduce a bunch more difficult to resolve merge conflicts. Oh well.

Some stuff I see that's still lost because of this PR at a first glance:
- All of the MediaSession logic
- The Discord integration isn't exactly the same yet (no change when seeking)
- The audio device option in the settings

**Comment by CaptSiro** [comment]
I tried it on Windows, and it hangs for me too... How are we going to resolve this?

**Comment by Tnixc** [comment]
Hmm I tested on mac and linux and it worked for me.

**Comment by brw** [comment]
Discord RPC is still giving errors but that'll be fixed after this is merged so LGTM for now. This is in a good enough state to build off from at least.

**Comment by duduBTW** [comment]
lgtm as well, we can polish thing out more once it is on master.

**Comment by Tnixc** [comment]
Lots of polishing to be done indeed

**Review by CaptSiro — APPROVED** [review]

**Comment by CaptSiro** [comment]
thank you for contributing :btmcLuv:

**Pull request merged**
